// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAxjJkphKOdGoDKQ1X9g72CC5CwS6qaHTg',
    appId: '1:926332260852:web:abd7cd5e26b921b114e9a1',
    messagingSenderId: '926332260852',
    projectId: 'subsparrow-4cca3',
    authDomain: 'subsparrow-4cca3.firebaseapp.com',
    storageBucket: 'subsparrow-4cca3.appspot.com',
    measurementId: 'G-801PVMDEY0',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCfimpavides0bLywqnIyYmhosD4SHbhJ8',
    appId: '1:926332260852:android:cddb4c6e4099432a14e9a1',
    messagingSenderId: '926332260852',
    projectId: 'subsparrow-4cca3',
    storageBucket: 'subsparrow-4cca3.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDnlyL-_tu9As3DOXDsyB4DxivFqmB77jE',
    appId: '1:926332260852:ios:96b0804b6e61cd1f14e9a1',
    messagingSenderId: '926332260852',
    projectId: 'subsparrow-4cca3',
    storageBucket: 'subsparrow-4cca3.appspot.com',
    iosBundleId: 'com.yasinertekin.subsparrow.subsparrow',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDnlyL-_tu9As3DOXDsyB4DxivFqmB77jE',
    appId: '1:926332260852:ios:1911ae35d01eec0014e9a1',
    messagingSenderId: '926332260852',
    projectId: 'subsparrow-4cca3',
    storageBucket: 'subsparrow-4cca3.appspot.com',
    iosBundleId: 'com.yasinertekin.subsparrow.subsparrow.RunnerTests',
  );
}
